import { PREFIX_CONST_REQUEST } from './base';

export const APP = {
  ...PREFIX_CONST_REQUEST('DRAWER', 'APP'),
};

export const QUESTION = {
  ...PREFIX_CONST_REQUEST('SEARCH', 'QUESTION'),
};

export const WORRY = {
  ...PREFIX_CONST_REQUEST('SEARCH', 'WORRY'),
  ...PREFIX_CONST_REQUEST('CREATE', 'WORRY'),
  ...PREFIX_CONST_REQUEST('UPDATE', 'WORRY'),
  ...PREFIX_CONST_REQUEST('DELETE', 'WORRY'),
};

export const QUIZ = {
  ...PREFIX_CONST_REQUEST('SEARCH', 'QUIZ'),
  ...PREFIX_CONST_REQUEST('CREATE', 'QUIZ'),
  ...PREFIX_CONST_REQUEST('UPDATE', 'QUIZ'),
  ...PREFIX_CONST_REQUEST('DELETE', 'QUIZ'),
};
