import { PREFIX_CONST_REQUEST } from './base';

export const QUESTION = {
  ...PREFIX_CONST_REQUEST('SEARCH', 'QUESTION'),
};

export const WORRY = {
  ...PREFIX_CONST_REQUEST('SEARCH', 'WORRY'),
  ...PREFIX_CONST_REQUEST('CREATE', 'WORRY'),
  ...PREFIX_CONST_REQUEST('UPDATE', 'WORRY'),
  ...PREFIX_CONST_REQUEST('DELETE', 'WORRY'),
};
