import { PREFIX_CONST_REQUEST } from './base';

export const APP = {
  ...PREFIX_CONST_REQUEST('DRAWER', 'APP'),
};

export const QUESTION = {
  ...PREFIX_CONST_REQUEST('SEARCH', 'QUESTION'),
};

export const WORRY = {
  ...PREFIX_CONST_REQUEST('SEARCH', 'WORRY'),
  ...PREFIX_CONST_REQUEST('CREATE', 'WORRY'),
  ...PREFIX_CONST_REQUEST('UPDATE', 'WORRY'),
  ...PREFIX_CONST_REQUEST('DELETE', 'WORRY'),
  ...PREFIX_CONST_REQUEST('DETAIL', 'WORRY'),
};

export const QUIZ = {
  ...PREFIX_CONST_REQUEST('SEARCH', 'QUIZ'),
  ...PREFIX_CONST_REQUEST('CREATE', 'QUIZ'),
  ...PREFIX_CONST_REQUEST('UPDATE', 'QUIZ'),
  ...PREFIX_CONST_REQUEST('DELETE', 'QUIZ'),
};

export const SETTING = {
  ...PREFIX_CONST_REQUEST('SEARCH', 'SETTING'),
  ...PREFIX_CONST_REQUEST('CREATE', 'SETTING'),
  ...PREFIX_CONST_REQUEST('UPDATE', 'SETTING'),
  ...PREFIX_CONST_REQUEST('RESCHEDULE', 'SETTING'),
};
