# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'anxietyCBT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Fabric'
  pod 'Crashlytics'

  # Pods for anxietyCBT

  target 'anxietyCBT-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'anxietyCBTTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
