fastlane_version "1.86.1"

default_platform :ios

platform :ios do
  # before_all do
  #   ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  # end

  def bump_build_version_ios
    branch_name = git_branch.sub("/","-")
    short_hash = get_build_number_repository

    increment_version_number(
      xcodeproj: "./ios/anxietyCBT.xcodeproj",
      version_number: "#{short_hash}.#{branch_name}"
    )
  end

  desc "Build and submit to Fabric"
  lane :beta do
    bump_build_version_ios

    cert

    build_app(
      scheme: "anxietyCBT",
      export_method: 'ad-hoc',
      project: "./ios/anxietyCBT.xcodeproj",
      export_xcargs: "-allowProvisioningUpdates"
    )

    crashlytics(
      notifications: true,
      groups:['internal-dev'],
      notes_path: "./fastlane/release-notes.beta.txt",
      crashlytics_path: "./ios/Pods/Crashlytics/submit",
      api_token: ENV['FABRIC_TOKEN'],
      build_secret: ENV['FABRIC_SECRET']
    )
  end

  # after_all do |lane|
  #   slack(channel: "deploys", message: "Successfully deployed new anxietyCBT alpha update to TestFlight.")
  # end
end

platform :android do
  # before_all do
  #   ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  # end

  def bump_build_version_android
    branch_name = git_branch.sub("/","-")
    short_hash = get_build_number_repository

    path = '../android/gradle.properties'
    re = /appVersionName=(.*)/

    s = File.read(path)
    s[re, 1] = "#{short_hash}.#{branch_name}.1.0.0"

    f = File.new(path, 'w')
    f.write(s)
    f.close
  end

  desc "Submit a new Alpha Build to Play Store"
  lane :beta do
    bump_build_version_android

    gradle(task: 'clean', project_dir: "./android") # Clean the Gradle project
    gradle(task: "assemble", build_type: "Release", project_dir: "./android") # Build the Release APK
    # supply(track: "alpha", apk: "android/app/build/outputs/apk/app-release.apk") # Upload the APK to the Play Store (alpha)

    crashlytics(
      notifications: true,
      groups:['internal-dev'],
      notes_path: "./fastlane/release-notes.beta.txt",
      apk_path: "./android/app/build/outputs/apk/release/app-release.apk",
      api_token: ENV['FABRIC_TOKEN'],
      build_secret: ENV['FABRIC_SECRET']
    )
    # slack(message: "Release new version")
  end
end
